import "./globals.css";

import { Abhaya_Libre } from "next/font/google";
import type { Metadata } from "next";
import SessionProvider from "./SessionProvider";

// const gfsDidot = GFS_Didot({
//   weight: ["400"],
//   subsets: ["greek"],
// });
const abhayaLibre = Abhaya_Libre({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={`${abhayaLibre.className} text-dark-brown`}>
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
