import "./globals.css";

import { GFS_Didot } from "next/font/google";
import type { Metadata } from "next";
import SessionProvider from "./SessionProvider";

const gfsDidot = GFS_Didot({
  weight: ["400"],
  subsets: ["greek"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={gfsDidot.className}>{children}</body>
      </SessionProvider>
    </html>
  );
}
